# Repository settings for safe-settings
# https://github.com/github/safe-settings

repository:
  # Repository name
  name: agentsilex

  # A short description of the repository that will show up on GitHub
  description: A transparent, minimal, and hackable agent framework. ~300 lines of readable code. Full control, no magic.

  # A URL with more information about the repository
  homepage: https://github.com/howl-anderson/agentsilex

  # A comma-separated list of topics to set on the repository
  topics:
    - ai-agent
    - llm
    - agent-framework
    - litellm
    - minimal
    - hackable
    - educational
    - python
    - pydantic
    - gemini
    - openai
    - anthropic

  # Either `true` to make the repository private, or `false` to make it public
  private: false

  # Either `true` to enable issues for this repository, `false` to disable them
  has_issues: true

  # Either `true` to enable projects for this repository, or `false` to disable them
  has_projects: true

  # Either `true` to enable the wiki for this repository, `false` to disable it
  has_wiki: false

  # Either `true` to enable downloads for this repository, `false` to disable them
  has_downloads: true

  # Updates the default branch for this repository
  default_branch: main

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  allow_squash_merge: true

  # Either `true` to allow merging pull requests with a merge commit, or `false` to prevent
  allow_merge_commit: true

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  allow_rebase_merge: true

  # Either `true` to enable automatic deletion of branches on merge, or `false` to disable
  delete_branch_on_merge: true